const initialState={role:'cfo',view:'cockpit',stage:'overview',approved:false,agent:'idle',task:0,completed:[],notice:''};
const saved=localStorage.getItem('fin-workspace-demo');
let state=saved?{...initialState,...JSON.parse(saved)}:{...initialState};
const navItems=[['cockpit','⌂','首页'],['workbench','✓','待办事项'],['forecast','⌁','滚动预测'],['resources','◒','资源配置'],['actions','▥','行动价值'],['cases','◇','决策事项'],['agents','♙','智能体'],['knowledge','▤','决策记忆']];
const tasks=[
 {id:'T-104',title:'校验 MVA Forecast Evidence',case:'DC-FC-DEMO-001',type:'待校验',due:'今天 11:00',risk:'高',desc:'检查 Server VN FY27 Q1 实际成本与 Forecast 驱动映射，确认 FX 数据质量异常。',input:'Actual v3、Forecast v2、FX driver file',output:'已复核 Evidence v4',next:'解锁驱动分析',mode:'hybrid'},
 {id:'T-109',title:'复核 Agent 驱动洞察',case:'DC-PR-DEMO-003',type:'待复核',due:'今天 14:00',risk:'中',desc:'验证库存 DOI 偏差洞察的证据引用，并判断因果措辞是否成立。',input:'Insight #17、库存 Evidence',output:'人工复核意见',next:'提交 FP&A Manager',mode:'hybrid'},
 {id:'T-112',title:'补充 Capex 利用率假设',case:'DC-RA-DEMO-002',type:'待补件',due:'明天 10:00',risk:'中',desc:'补充分期投资方案的设备利用率与现金影响假设。',input:'Capex 申请、产能模型',output:'Option v2 假设',next:'重新进入方案比较',mode:'human'},
 {id:'T-118',title:'发布已批准 Forecast',case:'DC-FC-DEMO-001',type:'待执行',due:'明天 12:00',risk:'高',desc:'按 CFO 附条件批准的授权边界发布 FY27 Q1 Forecast。原型仅模拟发布。',input:'Authorization DEMO-A09',output:'MOCK 发布回执',next:'创建准确性跟踪',mode:'agent'},
 {id:'T-121',title:'验证成本行动价值',case:'DC-PR-DEMO-003',type:'待验证',due:'周五 17:00',risk:'低',desc:'对比预期节省与实际成本变化，记录混杂因素。',input:'Action baseline、Actual v4',output:'Verification 结论',next:'事后评价',mode:'hybrid'}
];
const stageNames={overview:'决策封面',data:'数据',analysis:'分析',options:'方案',approval:'审批',tracking:'追踪',evaluation:'事后评价'};
function persist(){localStorage.setItem('fin-workspace-demo',JSON.stringify(state))}
function setState(patch){state={...state,...patch};persist();render()}
function money(n){return `${n<0?'-':''}$${Math.abs(n).toFixed(1)}M`}
function tag(text,color='blue'){return `<span class="tag ${color}">${text}</span>`}
function renderNav(){document.querySelector('#primary-nav').innerHTML=navItems.map(([id,icon,label])=>`<button class="nav-item ${state.view===id?'active':''}" data-nav="${id}"><span class="nav-icon">${icon}</span><span>${label}</span></button>`).join('')}
function shellHeader(title,sub,actions=''){return `<div class="page-head"><div><h2>${title}</h2><p>${sub}</p></div><div>${actions}</div></div>`}
function spark(color='#1768e5'){return `<svg class="spark" viewBox="0 0 90 30" aria-hidden="true"><path d="M2 24 C13 14 20 25 31 17 S49 23 59 10 S74 14 88 2" fill="none" stroke="${color}" stroke-width="2"/><path d="M2 29 L2 24 C13 14 20 25 31 17 S49 23 59 10 S74 14 88 2 L88 29Z" fill="${color}14"/></svg>`}
function forecastSvg(){return `<svg class="forecast-chart" viewBox="0 0 920 300" role="img" aria-label="Server VN MVA Actual Forecast Budget 趋势图">
 ${[45,95,145,195,245].map(y=>`<line x1="50" y1="${y}" x2="900" y2="${y}" class="chart-grid"/>`).join('')}
 <path d="M55 205 C115 190 145 213 205 181 S300 168 365 175 S440 150 505 158" fill="none" stroke="#174b9c" stroke-width="3"/>
 <path d="M505 158 C575 146 635 152 690 121 S790 105 895 82" fill="none" stroke="#1768e5" stroke-width="3" stroke-dasharray="9 7"/>
 <path d="M55 220 C180 207 300 204 505 194 S720 171 895 153" fill="none" stroke="#788ba8" stroke-width="2" stroke-dasharray="3 5"/>
 <path d="M505 138 C610 125 710 87 895 53 L895 111 C750 122 620 162 505 176Z" fill="#cfe1fb" opacity=".65"/>
 <line x1="505" y1="35" x2="505" y2="252" stroke="#9db4d2" stroke-dasharray="4 4"/><text x="515" y="52" class="chart-label">Forecast 区间</text>
 <circle cx="366" cy="175" r="12" fill="#df3f4c"/><text x="362" y="180" fill="#fff" font-size="12">1</text><circle cx="691" cy="121" r="12" fill="#e78619"/><text x="687" y="126" fill="#fff" font-size="12">2</text>
 ${['Oct','Nov','Dec','Jan','Feb','Mar','Apr','May','Jun'].map((x,i)=>`<text x="${60+i*103}" y="275" class="chart-label">${x}</text>`).join('')}
 <g transform="translate(275,292)"><line x1="0" x2="28" stroke="#174b9c" stroke-width="3"/><text x="34" y="4" class="chart-label">Actual</text><line x1="110" x2="138" stroke="#1768e5" stroke-width="3" stroke-dasharray="7 5"/><text x="144" y="4" class="chart-label">Forecast</text><line x1="235" x2="263" stroke="#788ba8" stroke-width="2" stroke-dasharray="3 4"/><text x="269" y="4" class="chart-label">Budget</text></g>
 </svg>`}
function cockpit(){return `<section class="page">${shellHeader(`早上好，${state.role==='cfo'?'CFO':'FP&A Analyst'}`,state.role==='cfo'?'今天有 3 项事项需要您的决策':'这是 CFO 决策视图，您当前以 Analyst 身份预览',`<button class="btn" data-role="${state.role==='cfo'?'analyst':'cfo'}">切换到${state.role==='cfo'?'执行':'CFO'}视图</button>`)}
 <div class="grid kpi-grid">
 ${[['Server VN MVA','28.6','+3.2% vs Forecast','negative','#df3f4c'],['预测 PTI','$84.2M','- $6.8M vs 上期','negative','#e78619'],['待审批影响','$126M','3 个 Decision Cases','', '#1768e5'],['已验证价值','$38.4M','82% 达成率','', '#0a9a91']].map(k=>`<div class="kpi-card"><div class="kpi-label"><span>${k[0]}</span><small>${k[0].includes('MVA')?'USD/Box':'USD'}</small></div><div class="kpi-value">${k[1]}</div>${spark(k[4])}<div class="kpi-delta ${k[3]}">${k[2]}</div></div>`).join('')}</div>
 <div class="grid dashboard-grid"><div class="stack">
 <article class="card"><div class="card-head"><h3>经营预测与风险 · Server VN</h3><div>${tag('月度','blue')} ${tag('FY27 Q1','gray')}</div></div><div class="card-body">${forecastSvg()}<div class="item-meta"><span class="variance-bad">● 异常 1：MVA 单台成本高于 Forecast 3.2%</span><span class="tag orange">● 驱动 2：FX 与 Mix 压力</span></div></div></article>
 <div class="grid" style="grid-template-columns:1fr 1fr"><article class="card ai-card"><div class="card-head"><h3><span class="ai-icon">✦</span> AI Insight</h3>${tag('模拟生成','blue')}</div><div class="card-body">${[['FX 不利变动贡献 1.4/Box','高置信度 86%','teal'],['高配置 Mix 提升贡献 0.9/Box','中置信度 71%','orange'],['间接人工效率为潜在驱动','待人工验证','orange']].map((x,i)=>`<div class="insight-row"><span class="insight-num">${i+1}</span><div style="flex:1">${x[0]}</div>${tag(x[1],x[2])}</div>`).join('')}<button class="btn" data-case-stage="analysis" style="margin-top:12px">查看完整分析 →</button></div></article>
 <article class="card"><div class="card-head"><h3>推荐方案</h3>${tag('需 CFO 决策','red')}</div><div class="card-body"><h3 style="margin-top:0">采用 FP&A 调整方案</h3><p style="color:var(--muted);line-height:1.55">调整 FX 与产品组合假设，FY27 Q1 MVA Outlook 更新至 27.8/Box，并附带每周 Mix 监控条件。</p><div class="item-meta"><span>PTI 影响 -$6.8M</span><span>置信度 78%</span></div><button class="btn primary" data-case-stage="options" style="margin-top:16px">比较 4 个方案</button></div></article></div></div>
 <aside class="stack"><article class="card"><div class="card-head"><h3>待我决策</h3><small>按紧急度</small></div><div class="card-body">${decisionItems()}</div></article><article class="card"><div class="card-head"><h3>Agent 运行状态</h3><button class="evidence-link" data-nav="agents">查看全部</button></div><div class="card-body"><div class="insight-row"><span class="insight-num">F</span><div><b>Forecast Agent</b><small style="display:block;color:var(--muted)">等待授权</small></div>${tag('待命','gray')}</div><div class="insight-row"><span class="insight-num" style="background:var(--teal)">P</span><div><b>Performance Agent</b><small style="display:block;color:var(--muted)">异常扫描</small></div>${tag('模拟运行','teal')}</div></div></article></aside></div></section>`}
function decisionItems(){return `<div class="decision-item" data-case-stage="overview"><div class="item-top"><span class="item-title"><i class="risk-dot">1</i>Server VN MVA Outlook</span>${tag('高','red')}</div><div class="item-meta"><span>影响 -$6.8M PTI</span><span>Owner: Lin Chen</span></div></div><div class="decision-item"><div class="item-top"><span class="item-title"><i class="risk-dot" style="background:var(--orange)">2</i>FY27 Capex 调整</span>${tag('中','orange')}</div><div class="item-meta"><span>申请 $18.0M</span><span>明天到期</span></div></div><div class="decision-item"><div class="item-top"><span class="item-title"><i class="risk-dot" style="background:#7890ad">3</i>库存 DOI 行动复盘</span>${tag('低','gray')}</div><div class="item-meta"><span>价值偏差 -$1.2M</span><span>待评价</span></div></div>`}
function workbench(){let t=tasks[state.task];return `<section class="page">${shellHeader('Finance Workbench',`早上好，FP&A Analyst · 今天有 ${tasks.filter(x=>!state.completed.includes(x.id)).length} 项待办`,`${tag('模拟工作日','blue')} <button class="btn" data-role="cfo">查看 CFO 视图</button>`)}<div class="filter-row">${['全部 5','今天 3','高风险 2','待 Agent 1','已完成 '+state.completed.length].map((x,i)=>`<button class="filter-chip ${i===0?'active':''}">${x}</button>`).join('')}</div><div class="grid workbench-grid">
 <aside class="card"><div class="card-head"><h3>我的待办</h3><small>按截止时间</small></div><div class="card-body">${tasks.map((x,i)=>`<div class="task-item ${state.task===i?'selected':''}" data-task="${i}"><div class="item-top"><b>${x.title}</b>${tag(x.risk,x.risk==='高'?'red':x.risk==='中'?'orange':'gray')}</div><div class="item-meta"><span><i class="task-status"></i>${x.type}</span><span>${x.due}</span></div><small style="display:block;color:var(--muted);margin-top:7px">${x.case}</small></div>`).join('')}</div></aside>
 <article class="card task-detail"><div class="card-head"><div><small style="color:var(--blue)">${t.id} · ${t.case}</small><h3>${t.title}</h3></div>${tag(state.completed.includes(t.id)?'已完成':t.type,state.completed.includes(t.id)?'teal':'orange')}</div><div class="card-body"><p style="color:var(--muted);line-height:1.6">${t.desc}</p><dl class="definition-list"><dt>为何给我</dt><dd>您是该 Case 的 FP&A Analyst</dd><dt>所需输入</dt><dd>${t.input}</dd><dt>期望产出</dt><dd>${t.output}</dd><dt>截止时间</dt><dd>${t.due}</dd><dt>完成后</dt><dd>${t.next}</dd></dl><h4>选择执行方式</h4><div class="grid mode-grid"><div class="mode-card ${t.mode==='human'?'selected':''}" data-mode="human"><h4>人工执行</h4><p>由您完成并对结果负责</p></div><div class="mode-card ${t.mode==='hybrid'?'selected':''}" data-mode="hybrid"><h4>Agent 草拟</h4><p>模拟准备，您复核确认</p></div><div class="mode-card ${t.mode==='agent'?'selected':''}" data-mode="agent"><h4>Agent 执行</h4><p>授权范围内模拟执行</p></div></div><div style="display:flex;gap:9px;margin-top:18px"><button class="btn primary" data-action="start-task">${t.mode==='human'?'开始工作':t.mode==='hybrid'?'生成模拟草稿':'启动模拟 Agent'}</button><button class="btn" data-case-stage="${t.id==='T-104'?'data':'tracking'}">打开 Decision Case</button></div></div></article>
 <aside class="stack"><article class="card"><div class="card-head"><h3>流程位置</h3></div><div class="card-body"><ul class="progress-list"><li class="done">Case 已触发</li><li class="active">${t.type} · 当前由您负责</li><li>${t.next}</li><li>后续审批 / 验证</li></ul></div></article><article class="card"><div class="card-head"><h3>团队与阻塞</h3></div><div class="card-body"><div class="insight-row"><div><b>2 项即将超时</b><small style="display:block;color:var(--muted)">需要今日处理</small></div>${tag('提醒','orange')}</div><div class="insight-row"><div><b>1 项等待业务输入</b><small style="display:block;color:var(--muted)">Capex 利用率</small></div>${tag('阻塞','red')}</div></div></article></aside></div></section>`}
function casePage(){return `<section class="page"><article class="card case-header"><div class="case-header-row"><div><small style="color:var(--blue);font-weight:700">DC-FC-DEMO-001 · 滚动预测</small><h2>Server VN MVA Outlook 更新</h2><div class="item-meta"><span>Owner: Lin Chen (FP&A)</span><span>截止：FY27 Q1 M1</span>${tag(state.approved?'已附条件批准':'待 CFO 审批',state.approved?'teal':'red')}${tag('模拟数据','gray')}</div></div><div><button class="btn" data-nav="${state.role==='cfo'?'cockpit':'workbench'}">返回${state.role==='cfo'?'Cockpit':'待办'}</button></div></div><div class="stage-track">${Object.entries(stageNames).map(([k,v])=>`<button class="${state.stage===k?'active':''}" data-stage="${k}">${state.approved&&k==='approval'?'✓ ':''}${v}</button>`).join('')}</div></article><div class="grid case-grid"><div>${caseMain()}</div><aside class="stack">${caseSummary()}${caseTimeline()}</aside></div></section>`}
function caseMain(){if(state.stage==='overview')return `<article class="card"><div class="card-head"><h3>决策封面</h3>${tag('影响重大','red')}</div><div class="card-body"><p style="font-size:17px;line-height:1.65">Server VN MVA 最新 Outlook 高于上一版 Forecast <b class="variance-bad">3.2%</b>。主要变化来自 FX、高配置产品 Mix 和间接人工效率，需要 CFO 在四个预测方案中作出选择并授权模拟发布。</p><dl class="definition-list"><dt>触发原因</dt><dd>MVA 超出 Forecast 风险阈值</dd><dt>影响范围</dt><dd>Server · VN Site · FY27 Q1</dd><dt>预计 PTI 影响</dt><dd class="variance-bad">-$6.8M</dd><dt>当前推荐</dt><dd>FP&A 人工调整方案 · 置信度 78%</dd><dt>反方观点</dt><dd>FX 可能短期回落，当前调整可能过度保守</dd><dt>所需决定</dt><dd>CFO 选择方案并确认发布条件</dd></dl><button class="btn primary" data-stage="data">从详细数据开始</button></div></article>`;
if(state.stage==='data')return `<div class="stack"><article class="card"><div class="card-head"><h3>MVA 数据视图</h3><div>${tag('Evidence v4','blue')} ${tag('质量已复核','teal')}</div></div><div class="card-body"><table class="metric-table"><thead><tr><th>指标</th><th>Budget</th><th>Forecast v2</th><th>Actual/最新</th><th>差异</th></tr></thead><tbody><tr><td>MVA / Box</td><td>26.5</td><td>27.7</td><td><b>28.6</b></td><td class="variance-bad">+3.2%</td></tr><tr><td>Volume (K)</td><td>820</td><td>795</td><td>768</td><td class="variance-bad">-3.4%</td></tr><tr><td>FX Index</td><td>100.0</td><td>101.2</td><td>103.8</td><td class="variance-bad">+2.6pt</td></tr><tr><td>High-config Mix</td><td>31%</td><td>34%</td><td>39%</td><td class="variance-bad">+5pt</td></tr></tbody></table><p style="margin-bottom:0"><button class="evidence-link" data-action="evidence">查看指标口径、来源与血缘 →</button></p></div></article><article class="card"><div class="card-head"><h3>数据质量记录</h3>${tag('已解决','teal')}</div><div class="card-body"><div class="insight-row"><span class="insight-num" style="background:var(--orange)">!</span><div><b>FX 驱动缺失 VN01 法人映射</b><small style="display:block;color:var(--muted);margin-top:4px">FP&A Analyst 已于 09:42 修正；Evidence v3 已保留，v4 可用于分析。</small></div></div></div></article><button class="btn primary" data-stage="analysis">进入驱动分析</button></div>`;
if(state.stage==='analysis')return `<div class="stack"><article class="card"><div class="card-head"><h3>MVA 差异驱动 Bridge</h3>${tag('vs Forecast v2','gray')}</div><div class="card-body"><div class="bridge">${[['27.7','Forecast',120,''],['+0.5','FX',72,'neg'],['+0.3','Mix',48,'neg'],['+0.2','人工',35,'neg'],['-0.1','物流',25,'pos'],['28.6','最新',158,'']].map(x=>`<div class="bridge-col"><b>${x[0]}</b><div class="bridge-bar ${x[3]}" style="height:${x[2]}px"></div><small>${x[1]}</small></div>`).join('')}</div></div></article><article class="card ai-card"><div class="card-head"><h3>✦ Agent 驱动洞察</h3>${tag('模拟 · 已人工复核','blue')}</div><div class="card-body"><div class="insight-row"><span class="insight-num">1</span><div><b>FX 不利变动贡献约 0.5/Box</b><small style="display:block;color:var(--muted)">Evidence E-104 · 置信度 86% · 已验证事实</small></div>${tag('接受','teal')}</div><div class="insight-row"><span class="insight-num">2</span><div><b>高配置 Mix 贡献约 0.3/Box</b><small style="display:block;color:var(--muted)">Evidence E-109 · 置信度 71% · 驱动候选</small></div>${tag('接受','teal')}</div><div class="insight-row"><span class="insight-num">3</span><div><b>间接人工效率下降导致单位成本上升</b><small style="display:block;color:var(--muted)">相关性充分，因果证据不足；Analyst 已降级为待验证假设</small></div>${tag('人工修正','orange')}</div></div></article><button class="btn primary" data-stage="options">比较决策方案</button></div>`;
if(state.stage==='options')return `<article class="card"><div class="card-head"><h3>方案比较</h3><small>基于 Evidence v4 · USD</small></div><div class="card-body">${[['A · 维持 Forecast v2','27.7 / Box','-$1.2M','46%','偏乐观',''],['B · Agent 建议','28.1 / Box','-$4.9M','74%','平衡',''],['C · FP&A 调整方案','27.8 / Box','-$3.2M','78%','推荐','recommended'],['D · 压力情景','29.4 / Box','-$12.6M','63%','保守','']].map(x=>`<div class="option-card ${x[5]}"><div class="item-top"><h4>${x[0]}</h4>${x[5]?tag('推荐','blue'):tag(x[4],'gray')}</div><div class="option-stats"><div><small>MVA</small><b>${x[1]}</b></div><div><small>PTI 影响</small><b>${x[2]}</b></div><div><small>置信度</small><b>${x[3]}</b></div><div><small>关键条件</small><b>${x[0][0]==='C'?'每周 Mix 监控':'—'}</b></div></div></div>`).join('')}<div class="approval-actions"><button class="btn" data-stage="analysis">返回分析</button><button class="btn primary" data-stage="approval">提交 CFO 审批</button></div></div></article>`;
if(state.stage==='approval')return `<article class="card"><div class="card-head"><h3>CFO 决策</h3>${tag(state.approved?'已批准':'需要您操作',state.approved?'teal':'red')}</div><div class="card-body"><div class="approval-box"><b>提交方案：C · FP&A 调整方案</b><p>MVA 27.8/Box · PTI 影响 -$3.2M · 置信度 78%</p><div class="item-meta"><span>Case v5</span><span>Evidence v4</span><span>Option C v2</span></div></div>${state.approved?`<div style="margin-top:18px">${tag('附条件批准','teal')}<p>条件：每周监控高配置 Mix；若超过 42%，重新提交 Forecast Case。</p><button class="btn primary" data-stage="tracking">查看执行追踪</button></div>`:`<div><label style="display:block;margin:18px 0 7px;font-weight:700">审批意见</label><textarea id="approval-note" style="width:100%;min-height:90px;border:1px solid var(--line);border-radius:8px;padding:12px;font:inherit">附条件批准：每周监控高配置 Mix；若超过 42%，重新提交。</textarea><div class="approval-actions"><button class="btn danger" data-action="reject">要求补件</button><button class="btn" data-action="approve">附条件批准</button><button class="btn primary" data-action="approve">批准方案 C</button></div></div>`}</div></article>`;
if(state.stage==='tracking')return `<div class="stack"><article class="card"><div class="card-head"><h3>执行追踪</h3>${tag(state.agent==='done'?'模拟发布完成':state.agent==='running'?'Agent 模拟运行中':'1 项待执行',state.agent==='done'?'teal':state.agent==='running'?'blue':'orange')}</div><div class="card-body"><table class="metric-table"><thead><tr><th>Action</th><th>Owner</th><th>截止</th><th>状态</th></tr></thead><tbody><tr><td>发布 FY27 Q1 Forecast</td><td>FP&A Analyst / Agent</td><td>明天</td><td>${state.agent==='done'?tag('已完成','teal'):tag('待执行','orange')}</td></tr><tr><td>每周监控 High-config Mix</td><td>FP&A Analyst</td><td>每周一</td><td>${tag('进行中','blue')}</td></tr><tr><td>验证预测准确性</td><td>FP&A Analyst</td><td>Q1 M2</td><td>${tag('未开始','gray')}</td></tr></tbody></table>${state.agent==='running'?`<div class="run-panel" style="margin-top:16px"><b>Forecast Agent · 模拟发布中</b><div class="run-loader"><span></span></div><small>正在校验 Authorization DEMO-A09…</small><div style="margin-top:12px"><button class="btn danger" data-action="stop-agent">停止并人工接管</button></div></div>`:state.agent==='done'?`<div class="run-panel" style="margin-top:16px"><b>MOCK-RECEIPT-27031</b><p style="margin-bottom:0">模拟发布完成 · 未连接任何企业系统 · 09:58</p></div>`:`<div style="margin-top:16px"><button class="btn primary" data-action="run-agent">交给 Agent 模拟执行</button> <button class="btn" data-action="human-complete">人工完成</button></div>`}</div></article><button class="btn primary" data-stage="evaluation">进入事后评价</button></div>`;
return `<article class="card"><div class="card-head"><h3>事后评价</h3>${tag('待 CFO 确认','orange')}</div><div class="card-body"><div class="grid kpi-grid" style="grid-template-columns:repeat(3,1fr)"><div class="kpi-card"><div class="kpi-label">批准基线</div><div class="kpi-value">27.8</div><small>MVA / Box</small></div><div class="kpi-card"><div class="kpi-label">实际结果</div><div class="kpi-value">28.0</div><small>MVA / Box</small></div><div class="kpi-card"><div class="kpi-label">准确率</div><div class="kpi-value">99.3%</div><small>较上一版提升 2.1pt</small></div></div><h4>评价结论</h4><p style="line-height:1.65;color:var(--muted)">方案方向正确，FX 判断基本兑现；Mix 改善慢于预期，造成 0.2/Box 偏差。每周监控条件及时暴露风险，执行到位。建议后续预测将 Mix 区间而非单点作为默认输入。</p><div class="approval-box"><b>Decision Memory 草稿</b><p>对高配置 Mix 波动较大的 Server VN 预测，采用范围假设并设置每周复核条件，比单点预测更稳健。</p></div><button class="btn primary" data-action="close-case" style="margin-top:16px">确认评价并关闭 Case</button></div></article>`}
function caseSummary(){return `<article class="card"><div class="card-head"><h3>持久决策摘要</h3></div><div class="card-body"><dl class="definition-list" style="grid-template-columns:88px 1fr"><dt>影响</dt><dd class="variance-bad">PTI -$6.8M 风险</dd><dt>推荐</dt><dd>方案 C · 27.8/Box</dd><dt>置信度</dt><dd>78% · 中高</dd><dt>主要风险</dt><dd>Mix 改善不及预期</dd><dt>材料</dt><dd>Evidence 4/4 已复核</dd><dt>下一步</dt><dd>${state.approved?'发布并追踪':'CFO 审批'}</dd></dl></div></article>`}
function caseTimeline(){return `<article class="card"><div class="card-head"><h3>决策时间线</h3></div><div class="card-body"><ul class="timeline"><li><strong>Evidence v4 已发布</strong>FP&A Analyst · 09:42</li><li><strong>Agent Insight 已复核</strong>因果表述降级为假设 · 09:48</li><li><strong>方案 C v2 已提交</strong>等待 CFO 决策 · 09:53</li>${state.approved?'<li><strong>CFO 附条件批准</strong>授权 DEMO-A09 · 09:56</li>':''}${state.agent==='done'?'<li><strong>模拟发布完成</strong>MOCK-RECEIPT-27031 · 09:58</li>':''}</ul></div></article>`}
function modulesPage(id){let map={forecast:['滚动预测','连接实际、驱动、预测建议、发布和准确性验证。','L2 · 代表页面','查看主预测 Case'],resources:['资源配置','管理 OPEX、HC 与 Capex 申请、方案、授权和使用监督。','L2 · 代表页面','查看示例申请'],actions:['行动与价值','跨 Decision Case 跟踪 Action、例外与价值实现。','L2 · 代表页面','查看主 Case 行动'],cases:['Decision Case Center','检索财务决策事项及其完整生命周期。','L1 · 入口介绍','进入示例 Case'],agents:['Agent 活动中心','查看 Agent Run、授权、停止、回执与人工接管。','L1 · 入口介绍','查看模拟 Run'],knowledge:['决策记忆','复用经审核的决策结果、适用条件和经验。','L1 · 入口介绍','查看经验卡'],admin:['管理与审计','配置角色、阈值、职责分离、代理与审计策略。','L1 · 入口介绍','查看能力说明']};let m=map[id]||map.cases;return `<section class="page">${shellHeader(m[0],m[1],tag(m[2],m[2].startsWith('L1')?'gray':'blue'))}<article class="card empty-panel"><div class="module-icon">◇</div><h2>${m[0]}</h2><p>${m[1]} 第一版原型仅保留本入口和代表性内容，不深入实现完整业务能力；相关对象仍可从主演示 Decision Case 中查看。</p><button class="btn primary" data-case-stage="${id==='forecast'?'data':id==='actions'?'tracking':'overview'}">${m[3]}</button></article><div class="grid module-grid" style="margin-top:14px">${[['主要输入','Decision Case、Evidence、角色范围'],['主要输出','状态、决策、行动或知识'],['未来能力','企业连接器、治理与规模化运行']].map(x=>`<article class="card module-card"><div class="module-icon">${x[0][0]}</div><h3>${x[0]}</h3><p>${x[1]}</p></article>`).join('')}</div></section>`}
function modal(title,body,actions){document.querySelector('#modal-root').innerHTML=`<div class="modal-backdrop"><div class="modal" role="dialog" aria-modal="true"><h3>${title}</h3>${body}<div class="modal-actions">${actions}</div></div></div>`}
function closeModal(){document.querySelector('#modal-root').innerHTML=''}
function toast(msg){let el=document.querySelector('#toast');el.textContent=msg;el.classList.add('show');setTimeout(()=>el.classList.remove('show'),2400)}
function render(){renderNav();document.querySelector('#role-name').textContent=state.role==='cfo'?'CFO':'FP&A Analyst';document.querySelector('#role-avatar').textContent=state.role==='cfo'?'C':'A';document.querySelector('#main-content').innerHTML=state.view==='cockpit'?cockpit():state.view==='workbench'?workbench():state.view==='case'?casePage():modulesPage(state.view);document.querySelector('#main-content').focus({preventScroll:true})}
document.addEventListener('click',e=>{let nav=e.target.closest('[data-nav]');if(nav){setState({view:nav.dataset.nav,stage:'overview'});return}let role=e.target.closest('[data-role]');if(role){state.role=role.dataset.role;state.view=state.role==='cfo'?'cockpit':'workbench';document.querySelector('#role-menu').hidden=true;persist();render();return}let cs=e.target.closest('[data-case-stage]');if(cs){setState({view:'case',stage:cs.dataset.caseStage});return}let stage=e.target.closest('[data-stage]');if(stage){setState({stage:stage.dataset.stage});return}let task=e.target.closest('[data-task]');if(task){setState({task:+task.dataset.task});return}let mode=e.target.closest('[data-mode]');if(mode){tasks[state.task].mode=mode.dataset.mode;render();return}let act=e.target.closest('[data-action]');if(!act)return;switch(act.dataset.action){case'reset':localStorage.removeItem('fin-workspace-demo');state={...initialState};render();toast('演示已重置');break;case'evidence':modal('Evidence E-104 · 数据血缘',`<p><b>模拟来源：</b>Mock Warehouse / server_vn_mva_actuals</p><p><b>期间：</b>FY27 Q1 M1 · <b>版本：</b>v4 · <b>质量：</b>已复核</p><p><b>处理：</b>法人映射 → 币种标准化 → MVA/Box 计算。所有数据均为合成数据。</p>`,`<button class="btn primary" data-action="close-modal">关闭</button>`);break;case'approve':modal('确认 CFO 审批',`<p>您将批准 <b>方案 C · FP&A 调整方案</b>，并签发一次模拟 Forecast 发布授权。</p><p>${tag('Case v5','gray')} ${tag('Evidence v4','gray')} ${tag('Option C v2','gray')}</p>`,`<button class="btn" data-action="close-modal">取消</button><button class="btn primary" data-action="confirm-approve">确认附条件批准</button>`);break;case'confirm-approve':closeModal();state.approved=true;state.stage='approval';persist();render();toast('已附条件批准并生成模拟授权');break;case'reject':toast('已退回 FP&A Analyst 补充材料');break;case'run-agent':state.agent='running';persist();render();setTimeout(()=>{if(state.agent==='running'){state.agent='done';persist();render();toast('模拟发布完成，已生成 MOCK 回执')}},3200);break;case'stop-agent':state.agent='stopped';persist();render();toast('Agent 已停止，任务已转为人工接管');break;case'human-complete':state.agent='done';persist();render();toast('已记录人工模拟完成');break;case'start-task':if(tasks[state.task].mode==='agent'){state.view='case';state.stage='tracking';state.agent='running';persist();render()}else{state.completed=[...new Set([...state.completed,tasks[state.task].id])];persist();render();toast('待办已完成，已流转到下一步骤')}break;case'close-case':toast('Decision Case 已完成模拟闭环');break;case'close-modal':closeModal();break}});
document.querySelector('#role-switch').addEventListener('click',()=>{let m=document.querySelector('#role-menu');m.hidden=!m.hidden});
render();
